version: "3"

networks:
  sagdevops_dbs:

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.baseoracle
    image: softwareag/base-oracle-xe-11g
    networks:
      - sagdevops_dbs
    ports:
      - "49160:22"
      - "49161:1521"
    environment: 
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ENABLE_XDB=false

  dbcreator:
    build:
      context: .
      dockerfile: Dockerfile
    image: softwareag/dbcreator
    networks:
      - sagdevops_dbs